#!/usr/bin/env bash

ask_for_sudo

### Get the .dot directory's absolute path
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
DOT_DIR="$(dirname "$SCRIPT_DIR")"

dir=~/.dot

### Get current dir (so run this script from anywhere)
export DOT_DIR
DOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

### Change to the dotfiles directory
echo "Changing directory to '$dir'..."
cd $dir

### Include functions
source "$dir/lib/functions.sh"

### Ask for confirmation
while true; do
    ask_for_confirmation "Warning: This shell will overwrite your current workspace setup. Proceed?"
    case $REPLY in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer, yes or no"
    esac
done

# *********************************************
# ************ ORDER IS IMPORTANT! ************
# *********************************************

### Install Xcode or skip if installed
sh "$dir/xcode/init.sh"

### Install Homebrew, Cask apps & Mas apps or update, upgrade & cleanup
sh "$dir/Homebrew/brew.sh"

### Setup Apache
sh "$dir/apache/init.sh"

### Install oh-my-zsh, symlink my config and inject my-config in `.zshrc`
sh "$dir/zsh/init.sh"

### Install Sublime-Text, symlink binary, install package-control and packages
sh "$dir/sublime-text/init.sh"

### PHP Configuration
sh "$dir/php/init.sh"

### Symlinking
declare -a FILES_TO_SYMLINK=(
    'symlinks/aliases.symlink'
    'symlinks/functions.symlink'
    'symlinks/gitconfig.symlink'
    'symlinks/gitignore_global.symlink'
)

symlinkDot ${FILES_TO_SYMLINK[@]}

### Setup macOS defaults as desired
sh "$dir/osx.sh"
