# OCD HITS: EVERYTHING SORTED IN ALPHABETICAL ORDER!

# Sources
tap 'caskroom/cask'
tap 'homebrew/apache'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/versions'

# Utilities
brew 'composer'
brew 'dnsmasq'
brew 'git'
brew 'httpd24', args: ['with-privileged-ports', 'with-http2']
brew 'mas'
brew 'mysql'
brew 'node'
brew 'php71', args: ['with-httpd24']
brew 'php71-mcrypt'
brew 'php71-xdebug'
brew 'python3'
brew 'redis'
brew 'sqlite'
brew 'unrar'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

# Apps from "Web"
cask 'alfred'
cask 'bartender'
cask 'dropbox'
cask 'flume'
# cask 'gitkraken'
cask 'google-chrome'
# cask 'iterm2'
cask 'phpstorm'
cask 'postman'
# cask 'razer-synapse'
# cask 'screenhero'
cask 'sequel-pro'
cask 'skype'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
# cask 'vanilla'
cask 'vlc'
# cask 'teamviewer'

# Apps from "App Store"
mas '1Password', id: 443987910
mas 'Bear', id: 1091189122
mas 'iA Writer', id: 775737590
mas 'Magnet', id: 441258766
mas 'Medis', id: 1063631769
mas 'Paste', id: 967805235
mas 'Pixelmator', id: 407963104
mas 'Screenflow', id: 1107828211
mas 'Transmit', id: 403388562
mas 'WinZip', id: 583827028
